import type {
  Project,
  CutList,
  CutSegment,
  Transcript,
  ExportOptions,
  GlobalSettings,
  MediaFile,
  WaveformPeaks,
  SubtitleConfig,
} from "./types";

// @ts-expect-error - bindings generated by wails3 build
import * as App from "../../bindings/smart-cut/app/app.js";

export async function createProject(name: string, mediaPath: string): Promise<Project> {
  return App.CreateProject(name, mediaPath);
}

export async function openProject(projectPath: string): Promise<Project> {
  return App.OpenProject(projectPath);
}

export async function saveProject(p: Project): Promise<void> {
  return App.SaveProject(p);
}

export async function getProject(projectID: string): Promise<Project> {
  return App.GetProject(projectID);
}

export async function getCutList(projectID: string): Promise<CutList> {
  return App.GetCutList(projectID);
}

export async function addCutSegment(projectID: string, seg: CutSegment): Promise<void> {
  return App.AddCutSegment(projectID, seg);
}

export async function updateCutSegment(projectID: string, seg: CutSegment): Promise<void> {
  return App.UpdateCutSegment(projectID, seg);
}

export async function removeCutSegment(projectID: string, segID: string): Promise<void> {
  return App.RemoveCutSegment(projectID, segID);
}

export async function startTranscribe(projectID: string): Promise<string> {
  return App.StartTranscribe(projectID);
}

export async function startAnalyze(projectID: string): Promise<string> {
  return App.StartAnalyze(projectID);
}

export async function startExport(projectID: string, opts: ExportOptions): Promise<string> {
  return App.StartExport(projectID, opts);
}

export async function getTranscript(projectID: string): Promise<Transcript> {
  return App.GetTranscript(projectID);
}

export async function getWaveform(projectID: string): Promise<string> {
  return App.GetWaveform(projectID);
}

export async function probeMedia(path: string): Promise<MediaFile> {
  return App.ProbeMedia(path);
}

export async function getSettings(): Promise<GlobalSettings> {
  return App.GetSettings();
}

export async function saveSettings(s: GlobalSettings): Promise<void> {
  return App.SaveSettings(s);
}

export async function probeBinary(name: string): Promise<{ path: string; version: string }> {
  return App.ProbeBinary(name);
}

export async function getWaveformPeaks(projectID: string): Promise<WaveformPeaks> {
  return App.GetWaveformPeaks(projectID);
}

export async function getMediaURL(projectID: string): Promise<string> {
  return App.GetMediaURL(projectID);
}

export async function getSubtitleConfig(projectID: string): Promise<SubtitleConfig> {
  return App.GetSubtitleConfig(projectID);
}
