// Code generated by Wails. DO NOT EDIT.
//
// This file is normally auto-generated by the Wails CLI tool when running
// `wails dev` or `wails build`. It is a stub created during frontend setup
// so that the Vite build can succeed before the Wails toolchain has been
// invoked. It will be replaced with real typed-event bindings on the next
// `wails dev` / `wails build` run.
